#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t Krexus"

$L ' __  __     ______     ______     __  __     __  __     ______';
$L '/\ \/ /    /\  == \   /\  ___\   /\_\_\_\   /\ \/\ \   /\  ___\';
$L '\ \  _"-.  \ \  __<   \ \  __\   \/_/\_\/_  \ \ \_\ \  \ \___  \';
$L ' \ \_\ \_\  \ \_\ \_\  \ \_____\   /\_\/\_\  \ \_____\  \/\_____\';
$L '  \/_/\/_/   \/_/ /_/   \/_____/   \/_/\/_/   \/_____/   \/_____/';
$L "Welcome to Android `getprop ro.build.version.release` / ROM version: `getprop ro.krexus.version`";
