add_lunch_combo krexus_angler-user
add_lunch_combo krexus_bullhead-user
add_lunch_combo krexus_flo-user
add_lunch_combo krexus_grouper-user
add_lunch_combo krexus_hammerhead-user
add_lunch_combo krexus_mako-user
add_lunch_combo krexus_shamu-user
